name: Notify

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Notify
        run: |
          curl https://api.github.com/repos/GLGDLY/intelligence_shoepad/dispatches \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -u ${{secrets.WORKFLOW_PAT}} \
          -d '{"event_type": "update", "client_payload": {}}'
